format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_spi}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_SPI_COMMON_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_spi, value: Asynchronous}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_spi}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_SPI_MODE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: Asynchronous}
      - type: Integer
        attributes: {id: DRV_SPI_NUM_CLIENTS}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '2'}
      - type: String
        attributes: {id: DRV_SPI_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: FLEXCOM5}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_spi_SPI_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: flexcom5}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: FLEXCOM5_SPI}
- type: ElementPosition
  attributes: {x: '165', y: '154', id: drv_spi}
